### ISSUE TITLE
[Feature] Multiple columns in the minibuffer

### ISSUE THREAD

**Issue by LouisKottmann** [creichert/ido-vertical-mode.el#11]
There's currently a lot of empty space on the right when using ido-vertical-mode, could it be used to display several columns of matches?

**Comment by creichert** [comment]
Another thought I had was using the empty space to show a `describe-function` or similar for the current selection. Minibuffer customization is somewhat limited compared to other buffers, though.

**Comment by larkery** [comment]
I have implemented something which packs multiple columns into the minibuffer based on its width - it is not tabulated list mode, but it works OK - see a5c72812a50fdfa0b642d7e8524b65070fdedcc3 .

It looks like this:

![2015-09-17-165358_863x205_scrot](https://cloud.githubusercontent.com/assets/1721963/9938291/8f375dd6-5d5c-11e5-8136-0cee4ecf78f2.png)

It doesn't let you move around in the grid, which is what I would like it to do. I haven't submitted a pull req. as it probably breaks all the tests (although if you say maximum 1 column then it should behave the same as before)

**Comment by LouisKottmann** [comment]
That looks awesome!

**Comment by larkery** [comment]
My master branch now has the ability to let you move around the grid with arrow keys. I am using it and find it OK - you might be interested.

**Comment by creichert** [comment]
@larkery This looks very cool, we should open a new PR for this one. As usual, I'd like tests but that's mostly for my own good in understanding the code and implementation. Nice!

**Comment by larkery** [comment]
I will likely rewrite my branch to have a nice tidy commit and some tests - the grid layout bits are quite amenable to testing as most of the work is nearly-pure functions. This might make some of the tests a bit more robust.

-----------------------

**Comment by larkery** [comment]
I have rewritten this from scratch, but I put it in a new package because I ended up breaking compatibility with existing ido-vertical-mode customizations. I don't want to upset people who just want vertical mode and found that an upgrade broke stuff they were happy with. It is at https://github.com/larkery/ido-grid-mode.el

**Comment by creichert** [comment]
Look really cool, congrats! Planning on releasing it to elpa?

**Comment by LouisKottmann** [comment]
Using it, it's great! However for easier .emacs.d maintenance I would love a package :)

**Comment by larkery** [comment]
I will try and work out how to do elpa/melpa type things once I'm sure it works reliably :) I am lazy and using `el-get` because it works off github repositories :)

**Comment by zakkak** [comment]
Just a heads up for anyone interested (@LouisKottmann).  The package is now in melpa. 

@creichert could you please add a reference to `ido-grid-mode` in the `Readme` file for people looking for this feature?

**Comment by LouisKottmann** [comment]
@zakkak thanks

**Comment by creichert** [comment]
@zakkak If you submit a PR to the README, I'll be happy to merge it. @larkery Really nice work
