### ISSUE TITLE
Allow setting custom indicators

### ISSUE THREAD

**Issue by marcwebbie** [creichert/ido-vertical-mode.el#28]
When there are matches ido-vertical-mode shows me "->". What about a variable to set our own matching character?

Thanks for the package, by the way.

**Comment by gempesaw** [comment]
Sure, sounds like a good idea and hopefully pretty straightforward to implement. Not sure when I'd get to it but I'd happily accept a PR :)

**Comment by marcwebbie** [comment]
Thanks guys
