### ISSUE TITLE
looking for maintainer for this package

### ISSUE THREAD

**Issue by gempesaw** [creichert/ido-vertical-mode.el#32]
As it says in the title, I don't have as much time or attention to dedicate to this package anymore.

The handoff should just be a simple repo transfer to a different github account, and we'd probably want to make a PR to MELPA for the new address (although I think github's redirecting may just handle it transparently...)

**Comment by creichert** [comment]
Darn,  this is a really great mode.  I could certainly give it a good home or help with maintenance. I consider it pretty stable so I would mostly keep it up-to-date with new Emacs and ido versions, although there are a few features I want to add.

**Comment by gempesaw** [comment]
@creichert hey, great! glad to see you're interested. i'll go ahead and begin the repo transfer - I think you'll need to confirm on your side. Let's see...

**Comment by creichert** [comment]
@gempesaw I removed my fork, Go ahead and try again. If you need anything feel free to ping me or message me. Thanks!

**Comment by gempesaw** [comment]
faaancy, thanks! i'll try to keep an eye on the issues & notifications, and i'm willing to pitch in if it's ever necessary... :)

**Comment by gempesaw** [comment]
@creichert  

https://github.com/milkypostman/melpa/blob/master/recipes/ido-vertical-mode

that looks like the file to modify in melpa :D

**Comment by creichert** [comment]
Done, https://github.com/milkypostman/melpa/pull/2878. Thanks!

**Comment by randymorris** [comment]
Just a heads up, I got a bunch of notifications that I was given push access to the new repo.  I haven't been a part of this since @gempesaw took over so you can freely remove me.  I don't have any investment in this package any longer as I've moved away from ido entirely.

**Comment by creichert** [comment]
Not sure why that happened but I removed you. Thanks for the notice.
