### ISSUE TITLE
Typing '[' is giving an error

### ISSUE THREAD

**Issue by nishantvarma** [creichert/ido-vertical-mode.el#35]
When you enabled ido-vertical-mode and open something like ido-swtich-buffer and type "["
you get an error saying thus:

Error in post-command-hook (ido-exhibit): (invalid-regexp "Unmatched [ or [^")

Is this a known issue?

**Comment by creichert** [comment]
Looks like a bug. I'll try to take a look at this asap unless you want to take a crack at it.

**Comment by nishantvarma** [comment]
Thanks. Will give it a try and update you if I find anything.

**Comment by creichert** [comment]
I'm still looking into this one, it's a bit tricky. It can also be
reproduced with two backslashes '\\'.

Nonetheless, I've written a test which I will push when I get things
working. Essentially just add `(should (string-match "[" prospects)) to
the first test in `test/ido-vertical-mode-test.el`. Hopefully, that will
prevent future issues.

**Comment by nishantvarma** [comment]
Great. Yeah its reproducible for anything that has special meaning in regex I guess.

**Comment by creichert** [comment]
@nishantvarma To clarify, regexp enabled was broken before and after the patch, right? Should we open a new issue for that?

There are many scenarios for insertion with and without regexp. So far, everything looks good but should keep hammering it and see if anything else crops up.  I'd like to get a few more use-cases in the test-suite to prevent breaking settings I don't use.

**Comment by nishantvarma** [comment]
@creichert : Thanks for merging PR :). Hope we are fine now. I think it should now handle both regexp enabled and regex disabled states. Both were broken before the patch.

If regex is disabled (which it is by default) then ideally we should not get a ido-incomplete-regex state so it will always apply formatting and it will always regexp quote the string so that special chars are made normal. (string-match) never gets an incomplete regex because it is quoted.

If regex is enabled then it can be both in incomplete regexp state or normal state. If its in incomplete regexp state its going to skip apply formatting because there is nothing to highlight. (string-match) will never get called. If regex is fine then it will supply the string normally but since we always have complete regex we should be fine. (string-match) always gets completex regex input.

I will go through the test cases and also keep hammering to see if we can find new scenarios.

**Comment by creichert** [comment]
Great, thanks again!
