### ISSUE TITLE
Problem switch-buffer when open new frame 

### ISSUE THREAD

**Issue by Enrico68** [creichert/ido-vertical-mode.el#39]
Hello,
I noticed that when I open a new frame switching to another buffer ido does not work properly. The problem is not present in first frame, This is an example of what is happening

http://i.imgur.com/PpP61Ne.gif

**Comment by creichert** [comment]
Thanks for the report, is this specifically an issue with ido-vertical-mode? The gif is moving a little quick, are you creating a new frame and then trying to `switch-buffer`?

**Comment by Enrico68** [comment]
Sorry for the speed (next time I will change the delay on gifsicle). Yes I saw the problem when I open a new frame (`make-frame`) and with the command `switch-to-buffer`. It looks that this just affects the new frame.

**Comment by Enrico68** [comment]
Updated now. It works. Sorry I did not run `Paradox` before ... :-)

**Comment by creichert** [comment]
Great, glad to know it's working.
