### ISSUE TITLE
Broken on latest emacs 27 branch

### ISSUE THREAD

**Issue by wyuenho** [creichert/ido-vertical-mode.el#48]
Commit in question: https://github.com/emacs-mirror/emacs/commit/3b0938c0420de2b845e7e8f8fbbb57ddc61718f2

Problems: prompt missing, and the completions left is not inserted after the current selection

**Comment by oscarfv** [comment]
Have you informed about this to the emacs developers?

**Comment by wyuenho** [comment]
No, but I don't think the completion display has ever been a public
interface anyway. If this brilliant hack of a package is to survive emacs
27,  it would be nice to find a way forward.

**Comment by oscarfv** [comment]
Probably checking for the symbol `ido--overlay` and removing the overlay would do.

In the meantime, `ido-grid-mode` seems unaffected by the change and it has an `ido-grid-mode-max-columns` parameter.

**Comment by wyuenho** [comment]
>> Probably checking for the symbol ido--overlay and removing the overlay would do.

That doesn't work. The overlay is added to the positioned completion list returned from `ido-vertical-completions`.

Ido-grid-* 's author hasn't answered on github for 4 years, and the new implementation isn't on Melpa and it's bugs and PRs aren't even merged.

Is there anything we can do to `ido-vertical-completion` to fix this issue for emacs-27?

**Comment by wyuenho** [comment]
Actually, deleting the overlay just deletes the vertical list altogether.

**Comment by dgutov** [comment]
What do you mean, no prompt? It's right there, at the top of the minibuffer.

And to put the cursor where it should be, start the completions string with a space:

```el
             (concat
              " "
              ;; put in common completion item -- what you get by pressing tab
```

**Comment by wyuenho** [comment]
@dgutov The prompt I mean is the find-file prompt, before emacs-mirror/emacs@3b0938c, it looks like this:

<img width="478" alt="Screen Shot 2020-02-01 at 13 43 30" src="https://user-images.githubusercontent.com/160028/73593181-e901aa00-44f8-11ea-895d-e75f124f6a97.png">

Now it looks like this:

<img width="478" alt="Screen Shot 2020-02-01 at 14 01 58" src="https://user-images.githubusercontent.com/160028/73593368-71814a00-44fb-11ea-8938-fe53feb532e8.png">

**Comment by nverno** [comment]
Just noticed this as well after recent build.  It certainly makes ido-vertical-mode much more confusing to use.

**Comment by dgutov** [comment]
> The prompt I mean is the ido-find-file prompt

OK, now I see that. Couldn't reproduce this part of the problem the previous time I tried. But since Eli might have a fix for that soon-ish, try my suggestion for the cursor problem.

**Comment by ctrl2wei** [comment]
@dgutov I don't use this package, but how I fix this
```
emacs -Q
M-x ido-mode
M-: (setq ido-max-window-height 1)
```
this gets same issue even after 4a0a11

**Comment by oscarfv** [comment]
@ctrl2wei : please use `M-x report-emacs-bug` to send your bug report to the Emacs maintainers. Your issue has nothing to do with `ido-vertical-mode` and belongs to Emacs proper.

**Comment by dgutov** [comment]
@ctrl2wei @oscarfv I've filed http://debbugs.gnu.org/cgi/bugreport.cgi?bug=39433

**Comment by wyuenho** [comment]
This appears to have been fixed.
