### ISSUE TITLE
cl-loop not being expanded during compile

### ISSUE THREAD

**Issue by nverno** [creichert/ido-vertical-mode.el#50]
I'm not sure what has changed, but on a new install with emacs 28.0.50, I was running into problems using `ido-vertical-mode` that I traced to the `cl-loop` not being expanded in `ido-vertical-completions` (I was seeing an `unbound for` error in the `post-command-hook` during completions).  Simply recompiling with cl-lib required solved the problem, or adding `(eval-when-compile (require 'cl-lib))`

**Comment by wyuenho** [comment]
See #49 and #51

**Comment by creichert** [comment]
#49 is merged which should fix the issue. Sorry for the delay.
