### ISSUE TITLE
Error in post-command-hook (ido-exhibit): (void-variable for) [Emacs 27.1]

### ISSUE THREAD

**Issue by ianpan870102** [creichert/ido-vertical-mode.el#51]
Please kindly refer to this Reddit thread for more details: https://www.reddit.com/r/emacs/comments/ie4za0/ido_error/

**Comment by wyuenho** [comment]
#49 is the fix

**Comment by creichert** [comment]
#49 is merged now so this issue should be resolved. Really sorry about the delay.
